In [3]:
import numpy as np

import pandas as pd

from pandas import Series,DataFrame

from pandas import read_html

In [4]:
url ="https://en.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_GDP"

In [5]:
dframe_list=pd.io.html.read_html(url)

In [6]:
dframe=dframe_list[2]

In [7]:
dframe

,0,1,2,3,4,5
0,Rank,Rank(50 states),State or territory,2017,% of Nation,Region
1,—,—,United States,"19,263,350[B]",100.00[B],NaN
2,1,1,California,2746873,14.17,West
3,2,2,Texas,1696206,8.64,South
4,3,3,New York,1547116,8.10,Northeast
5,4,4,Florida,967337,5.00,South
6,5,5,Illinois,820362,4.30,Midwest
7,6,6,Pennsylvania,752071,3.89,Northeast
8,7,7,Ohio,649127,3.39,Midwest
9,8,8,New Jersey,591743,3.11,Northeast
10,9,9,Georgia,554269,2.87,South
11,10,10,North Carolina,538291,2.82,South
12,11,11,Massachusetts,527455,2.73,Northeast
13,12,12,Virginia,508662,2.66,South
14,13,13,Washington,506353,2.58,West
15,14,14,Michigan,504967,2.65,Midwest
16,15,15,Maryland,393632,2.07,South
17,16,16,Indiana,359122,1.88,Midwest
18,17,17,Minnesota,351113,1.83,Midwest
19,18,18,Tennessee,345218,1.79,South
20,19,19,Colorado,342748,1.74,West
21,20,20,Wisconsin,324061,1.69,Midwest
22,21,21,Arizona,319850,1.65,West
23,22,22,Missouri,304898,1.62,Midwest
24,23,23,Connecticut,260827,1.40,Northeast
25,24,24,Louisiana,246264,1.28,South
26,25,25,Oregon,236219,1.24,West
27,26,26,South Carolina,219093,1.13,South
28,27,27,Alabama,210954,1.11,South
29,28,28,Kentucky,202507,1.06,South
30,29,29,Iowa,190191,1.00,Midwest
31,30,30,Oklahoma,189160,0.98,South
32,31,31,Utah,165526,0.85,West
33,32,32,Kansas,157797,0.81,Midwest
34,33,33,Nevada,156313,0.79,West
35,34,—,District of Columbia,131010,0.68,South
36,35,34,Arkansas,124918,0.66,South
37,36,35,Nebraska,121774,0.63,Midwest
38,37,36,Mississippi,111707,0.59,South
39,38,—,Puerto Rico,103135,0.55[A],NaN
40,39,37,New Mexico,97090,0.51,West
41,40,38,Hawaii,88136,0.46,West
42,41,39,New Hampshire,80516,0.42,Northeast
43,42,40,West Virginia,76794,0.39,South
44,43,41,Delaware,73541,0.39,South
45,44,42,Idaho,71886,0.37,West
46,45,43,Maine,61404,0.32,Northeast
47,46,44,Rhode Island,59458,0.31,Northeast
48,47,45,North Dakota,55493,0.29,Midwest
49,48,46,Alaska,52789,0.27,West
50,49,47,South Dakota,49928,0.26,Midwest
51,50,48,Montana,48098,0.25,West
52,51,49,Wyoming,40286,0.21,West
53,52,50,Vermont,32197,0.17,Northeast
54,53,—,Guam,5793,0.03[A],NaN
55,54,—,US Virgin Islands,3765,0.02[A],NaN
56,55,—,Northern Mariana Islands,1242,0.006[A],NaN
57,56,—,American Samoa,658,0.003[A],NaN

In [8]:
DataFrame(dframe,columns=[2,3]).rename(columns=["States","GDP"])

TypeError: 'list' object is not callable